/** Live Chromium rehearsal against the real backend and Next.js UI. */
import {chromium, expect} from '../frontend/node_modules/@playwright/test/index.mjs';
import {mkdirSync, writeFileSync} from 'node:fs';
import path from 'node:path';
const baseURL = process.env.MERIDIAN_UI_URL || 'http://127.0.0.1:3000';
const output = path.resolve('docs/screenshots'); mkdirSync(output, {recursive:true});
const executablePath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
const browser = await chromium.launch({headless:true, ...(executablePath ? {executablePath, args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']} : {})});
const errors = [];
const checks = [];
try {
  const page = await browser.newPage({viewport:{width:1512,height:1080}});
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(baseURL, {waitUntil:'networkidle', timeout:60000});
  await expect(page.getByRole('button',{name:'Analyze advisory'})).toBeEnabled({timeout:20000});
  await expect(page.getByTestId('system-recommendation')).toHaveCount(0);
  checks.push('No clinical recommendation before analysis');
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'workspace.png'), fullPage:true});
  await page.getByRole('button',{name:'Analyze advisory'}).click();
  await expect(page.getByTestId('system-recommendation')).toHaveText('Clinician within 24 hours');
  await expect(page.getByRole('button',{name:/Accept recommendation/})).toBeEnabled();
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'demo-a-advisory.png'), fullPage:true});
  await page.getByRole('tab',{name:/Evidence/}).click();
  await expect(page.getByText('Verified guidance', {exact:true})).toBeVisible();
  await expect(page.getByText('SYNTHETIC DEMONSTRATION ONLY.', {exact:false}).first()).toBeVisible();
  await page.getByRole('tab',{name:'Overview',exact:true}).click();
  await page.getByRole('button',{name:/Accept recommendation/}).click();
  await page.getByLabel(/Clinical documentation/).fill('Nurse reviewed the synthetic context, missing information and validated advisory.');
  await page.getByRole('button',{name:'Save documented action'}).click();
  await expect(page.locator('.decision-status')).toHaveText('Accepted');
  await expect(page.locator('.outcome-row')).toContainText('Unrecorded');
  await page.getByRole('button',{name:/Every decision, traceable/}).click();
  await expect(page.getByRole('dialog',{name:'Audit trail'})).toBeVisible();
  await expect(page.getByText('Nurse action committed', {exact:true})).toBeVisible();
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'audit-trail.png'), fullPage:true});
  await page.getByRole('button',{name:'Close audit trail'}).click();
  checks.push('Demo A: evidence, clinician advisory, nurse acceptance, audit; no inferred patient consent');

  await page.getByRole('button',{name:/Safety & patient choice/}).click();
  await expect(page.getByRole('button',{name:'Analyze advisory'})).toBeEnabled();
  await page.getByRole('button',{name:'Analyze advisory'}).click();
  await expect(page.getByTestId('system-recommendation')).toHaveText('Emergency department');
  await expect(page.getByText('Safety lock active',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:/Document patient refusal/}).click();
  await page.getByLabel(/Patient's stated preference/).fill('I choose to remain home in this synthetic demonstration.');
  await page.getByLabel(/Clinical documentation/).fill('Discussed the synthetic recommendation and documented patient refusal.');
  await page.getByRole('button',{name:'Save documented action'}).click();
  await expect(page.locator('.decision-status')).toHaveText('Declined by patient');
  await expect(page.getByTestId('system-recommendation')).toHaveText('Emergency department');
  await expect(page.locator('.recommendation-card')).toHaveClass(/danger/);
  await expect(page.locator('.outcome-row')).toContainText('Remains home');
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'demo-b-refusal.png'), fullPage:true});
  checks.push('Demo B: ED safety lock and refusal persist as separate states; emergency styling preserved');

  await page.getByLabel('Scenario picker').selectOption('llm-timeout');
  await expect(page.getByRole('button',{name:'Analyze advisory'})).toBeEnabled();
  await page.getByRole('button',{name:'Analyze advisory'}).click();
  await expect(page.getByTestId('system-recommendation')).toHaveText('Manual clinical review');
  await expect(page.getByText('AI synthesis unavailable — manual clinical review required.')).toBeVisible();
  await expect(page.getByRole('button',{name:/Accept recommendation/})).toBeDisabled();
  await expect(page.getByRole('button',{name:/Escalate to clinician/})).toBeEnabled();
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'manual-mode.png'), fullPage:true});
  checks.push('Outage: explicit manual mode, acceptance disabled, escalation available');

  await page.getByLabel('Scenario picker').selectOption('home-complete');
  await expect(page.getByRole('button',{name:'Analyze advisory'})).toBeEnabled();
  await page.getByRole('button',{name:'Analyze advisory'}).click();
  await expect(page.getByTestId('system-recommendation')).toHaveText('Home monitoring');
  await page.getByLabel('Patient transcript').fill('Maybe I have chest pain; I am unsure.');
  await expect(page.getByRole('button',{name:/Accept recommendation/})).toBeDisabled();
  await page.getByRole('button',{name:'Analyze advisory'}).click();
  await expect(page.getByTestId('system-recommendation')).toHaveText('Manual clinical review');
  checks.push('Complete home positive control; edits disable decisions and uncertain new input requires manual review');

  await page.getByLabel('Demo identity').selectOption('clinician-morgan');
  await expect(page.getByRole('button',{name:/Clinician override/})).toBeVisible();
  await page.getByRole('button',{name:/Clinician override/}).click();
  await page.getByLabel('Requested disposition').selectOption('CLINICIAN_WITHIN_24H');
  await page.getByLabel(/Clinical documentation/).fill('Synthetic clinician independently reviewed this manual case.');
  await page.getByRole('button',{name:'Save documented action'}).click();
  await expect(page.locator('.decision-status')).toHaveText('Overridden');
  await expect(page.getByTestId('system-recommendation')).toHaveText('Manual clinical review');
  checks.push('Authorized clinician override records a separate human decision without changing advisory');

  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:/Everyday uncertainty/}).click();
  await expect(page.getByRole('button',{name:'Analyze advisory'})).toBeEnabled();
  const overflow = await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth + 1);
  if(overflow) throw new Error('Mobile layout overflows horizontally.');
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:path.join(output,'mobile-workspace.png'),fullPage:true});
  checks.push('390px responsive layout: no horizontal overflow');
  if(errors.length) throw new Error('Browser console errors: '+errors.join('; '));
  const login = await (await page.request.post(baseURL+'/api/auth/demo',{data:{actorId:'nurse-avery'}})).json();
  const metrics = await (await page.request.get(baseURL+'/api/metrics',{headers:{Authorization:'Bearer '+login.accessToken}})).json();
  if(metrics.timeToSafeRender.samples < 1) throw new Error('Safe-render telemetry was not recorded.');
  const result = {passed:true, checks, pageErrors:errors.length, screenshots:'docs/screenshots', metrics};
  writeFileSync('docs/browser-rehearsal.json', JSON.stringify(result,null,2)+'\n');
  console.log(JSON.stringify(result,null,2));
} finally {await browser.close();}
